name: Schedule Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: "11,26,41,56 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test schedule
        run: date -u
